config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :polls, :users
  resources :votes, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "polls#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower < ApplicationRecord
  has_many :users
  belongs_to :user
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :user

  has_many :votes
  has_many :users, through: :votes



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :followers
         has_many :votes

         has_many :polls, through: :votes
         has_many :polls
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :poll
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
 def index
   @polls = Poll.all
 end

 def show
   @poll = Poll.find(params[:id])
 end

 def new
   @poll = Poll.new
 end

 def create
   @poll = Poll.create(poll_params)

   redirect_to @poll
 end

 private

 def poll_params
   params.require(:poll).permit(:user_id, :question, :answer_one, :answer_two)
 end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def index
   @users = User.all
 end

 def show
   @user = User.find(params[:id])
 end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

 def create
   voting_user = User.find_by(username: current_user.username)
   params[:button] == 'true' ? params[:button] = true : params[:button] = false
   @vote = Vote.create(user_id: voting_user.id, poll_id: params[:poll_id], vote: params[:button])
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iVote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="<%= root_path %>">iVote</a>
      </div>

    <% if user_signed_in? %>
      <div class="navbar-menu">
        <a class="navbar-item" href="<%= polls_path %>">Polls</a>
        <a class="navbar-item" href="<%= users_path %>">Users</a>
        <a class="navbar-item" href="<%= edit_user_registration_path(current_user.name) %>">Profile</a>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class:'navbar-item' %>

      </div>
    <% else %>
      <div class="navbar-menu">
        <a class="navbar-item" href="<%= new_user_session_path %>">Sign In</a>
        <a class="navbar-item" href="<%= new_user_registration_path %>">Sign Up</a>
      </div>
    <% end %>

  </nav>


    <%= yield %>
  </body>

  <footer class="footer">
      <div class="content has-text-left">
        <p>
          <strong>iVote©</strong> by Kai & Fez.
        </p>
      </div>
  </footer>
</html>

app/views/polls/index.html.erb
<div class="container is-fluid" style="margin-top:20px; margin-bottom:20px;">


  <% @polls.each do |poll| %>
    <div class="box is-centered" style="text-align: center;">
      <h1 style="font-size:2em"><%= poll.question %></h1><br>

      <h2 style="font-size:1.5em">

        <%= form_tag(votes_path) %>

          <%= hidden_field_tag 'poll_id', "#{poll.id}" %>

          <%= button_tag(type: 'submit', class: "button is-danger", value: true) do %>
            <% content_tag(:strong, poll.answer_one) %>
          <% end %>
          or
          <%= button_tag(type: 'submit', class: "button is-success", value: false) do %>
            <% content_tag(:strong, poll.answer_two) %>
          <% end %>

        </form>

      </h2><br>

      <%= green = (((Vote.all.where(poll_id: poll.id, vote: true).count).to_f/(Vote.all.where(poll_id: poll.id).count).to_f)*100).round %>%
      <%= red = 100-green%>%


      <h5 style="font-size:0.8em">Created by:<%= poll.user.username %></h5>
    </div>
  <% end %>

</div>

app/views/polls/new.html.erb
<h1>Create new Poll</h1>

<%= form_for @poll do |f| %>
  <%= f.label :question %>
  <%= f.text_field :question %><br>
  <%= f.label :answer_one %>
  <%= f.text_field :answer_one %><br>
  <%= f.label :answer_two %>
  <%= f.text_field :answer_two %><br>
  <%= f.label :user_id %>
  <%= collection_select(:poll, :user_id, User.all, :id, :username) %><br>
  <%= f.submit %>
<% end %>

app/views/polls/show.html.erb
<h1><%= @poll.question %></h1>
<h2><%= @poll.answer_one %> OR <%= @poll.answer_two %></h2>
<h5><%= @poll.user.username %></h5>